/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', "[data-theme='dark']"],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        gray: { 925: '#050814' },
        // Material Design 3 color tokens
        'primary':                    '#050f36',
        'primary-container':          '#1b254b',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#838db9',
        'on-primary-fixed':           '#0e193e',
        'on-primary-fixed-variant':   '#3b456c',
        'primary-fixed':              '#dde1ff',
        'primary-fixed-dim':          '#bbc4f4',
        'inverse-primary':            '#bbc4f4',
        'secondary':                  '#b36b00',
        'secondary-container':        '#f6ad55',
        'secondary-fixed':            '#fde8cb',
        'secondary-fixed-dim':        '#f6ad55',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#7c4500',
        'on-secondary-fixed':         '#331a00',
        'on-secondary-fixed-variant': '#7c4500',
        'tertiary':                   '#4a5568',
        'tertiary-container':         '#64748b',
        'tertiary-fixed':             '#e2e8f0',
        'tertiary-fixed-dim':         '#cbd5e1',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#94a3b8',
        'on-tertiary-fixed':          '#1e293b',
        'on-tertiary-fixed-variant':  '#475569',
        'surface':                    '#f8f9ff',
        'surface-bright':             '#f8f9ff',
        'surface-dim':                '#ccdbf4',
        'surface-container':          '#e5eeff',
        'surface-container-high':     '#dce9ff',
        'surface-container-highest':  '#d4e4fc',
        'surface-container-low':      '#eff4ff',
        'surface-container-lowest':   '#ffffff',
        'surface-variant':            '#d4e4fc',
        'surface-tint':               '#535c86',
        'on-surface':                 '#0d1c2e',
        'on-surface-variant':         '#45464e',
        'on-background':              '#0d1c2e',
        'background':                 '#f8f9ff',
        'outline':                    '#718096',
        'outline-variant':            '#cbd5e1',
        'inverse-surface':            '#223144',
        'inverse-on-surface':         '#eaf1ff',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      fontFamily: {
        display:  ['"Manrope"',        'ui-sans-serif', 'system-ui', 'sans-serif'],
        body:     ['"Manrope"',        'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'ui-monospace',  'SFMono-Regular', 'monospace'],
        headline: ['"Manrope"',        'ui-sans-serif', 'system-ui', 'sans-serif'],
        label:    ['"Manrope"',        'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseAccent: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
        slideDownAndFade: {
          '0%':   { opacity: '0', transform: 'translateY(-6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUpAndFade: {
          '0%':   { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        hide: {
          '0%':   { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'fade-up':          'fadeUp 0.55s ease both',
        'fade-in':          'fadeIn 0.4s ease both',
        'pulse-accent':     'pulseAccent 2.2s ease infinite',
        'shimmer':          'shimmer 1.8s linear infinite',
        'slide-down-fade':  'slideDownAndFade 150ms cubic-bezier(0.16,1,0.3,1)',
        'slide-up-fade':    'slideUpAndFade 150ms cubic-bezier(0.16,1,0.3,1)',
        'hide':             'hide 150ms ease',
      },
    },
  },
  plugins: [],
}
